package controller;

import java.awt.event.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import model.*;
import view.*;

/**
 * Controller class, acts as an intermediary between view and model defines what
 * should happen on user interaction
 * @author Kjell Treder
 * @author Marcel Sauer
 */

public class KinoController extends KeyAdapter implements ActionListener, ItemListener, ChangeListener {

    // References to view and model
    private KinoView view;
    private KinoModel model;

    /**
     * Constructor, assigns references to view and model
     * @param view reference to the view object
     * @param model reference to the model object
     */
    public KinoController(KinoView view, KinoModel model) {
        this.view = view;
        this.model = model;
    }

    /**
     * invoked when user interacts with a JButton, JRadioButton or JCheckBox
     * @param e the event generated by the component with the listener
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("\n" + "DEBUG: " + "ctrl: click registered..."); // DEBUG
        Object source = e.getSource();
        String cmd = e.getActionCommand();
        if (source instanceof JButton) { // source from JButton > source is either back-, quit or proceedbutton
            if (cmd.equals(Vocabulary.BACK_BUTTON)) 
                view.back();
            else if (cmd.equals(Vocabulary.QUIT_BUTTON))
                model.quit();
            else if (cmd.equals(Vocabulary.PROCEED_BUTTON)) 
                view.proceed();
            else if (cmd.equals(Vocabulary.FINISH_BUTTON)) {
                view.finish();
                model.order();
                view.update();
            }
        } else if (source instanceof JRadioButton) { // source from JRadioButton > source is from time tab
            System.out.println("DEBUG: " + "ctrl: Time chosen"); // DEBUG
            int index = Integer.parseInt(cmd);
            model.setTime(index);
            view.update();
        } else if (source instanceof JCheckBox) { // source from JCheckBox > source is from seat tab
            seatChanged();
        }
    }

    /**
     * invoked when user interacts with a JComboBox > movie selected
     * @param e the event generated by the component with the listener
     */
    @Override
    public void itemStateChanged(ItemEvent e) {
        System.out.println("\n" + "DEBUG: " + "ctrl: click registered..."); // DEBUG
        System.out.println("DEBUG: " + "ctrl: Movie chosen"); // DEBUG
        Movie movie = (Movie) e.getItem(); // get the selected movie from the JComboBox
        if (movie != null) // check if an actual movie is selected
            model.setMovie(movie); // model receives the movie
        view.update();
    }

    /**
     * invoked when user interacts with a JTextField by typing
     * @param e the event generated by the component with the listener
     */
    @Override
    public void keyReleased(KeyEvent e) {
        System.out.println("\n" + "DEBUG: " + "ctrl: key type registered..."); // DEBUG
        view.update(); // source is from JTextField > source from seat tab
    }

    /**
     * invoked when user interacts with a JSpinner
     * @param e the event generated by the component with the listener
     */
    @Override
    public void stateChanged(ChangeEvent e) {
        System.out.println("\n" + "DEBUG: " + "ctrl: click registered..."); // DEBUG
        cateringChanged(); // source is from JSpinner > source from catering tab
    }

    /**
     * invoked from event, searches for chosen seats in view
     * advises model to change chosen seats
     * updates view
     */
    private void seatChanged() { // TODO update this logic
        System.out.println("DEBUG: " + "ctrl: Seat chosen"); // DEBUG
        SeatingTab tab = (SeatingTab) view.tabs[3]; // get reference to the seating tab from the view
        JCheckBox[][] cbs = tab.getCheckBoxes(); // get reference to all JCheckBoxes from the tab
        int rowAmount = cbs.length; // amount of rows of JCheckBoxes
        int columnAmount = cbs[0].length; // amount of columns of JCheckBoxes

        List<Seat> seats = new ArrayList<>(); // create a new list, which will contain every selected seat
        for (int row = 0; row < rowAmount; row++) { // every row
            for (int column = 0; column < columnAmount; column++) { // checks every column of every row
                JCheckBox currentCB = cbs[row][column]; // get the JCheckBox at the current row and column position
                if (currentCB.isSelected()) { // JCheckBox is selected
                    Seat equivalentSeat = model.availableSeats[row][column]; // get the seat at position row|column from the model, which is equivalent to the position of the JCheckBox
                    seats.add(equivalentSeat); // add the seat to the list
                }
            }
        }
        model.setSeats(seats); // model receives the new list
        view.update();
    }

    /**
     * invoked from event, gets setting from all SpinnerNumberModels
     * advises model to change chosen caterings
     * updates view
     */
    private void cateringChanged() { // TODO update this logic
        System.out.println("DEBUG: " + "ctrl: Catering chosen"); // DEBUG
        CateringTab tab = (CateringTab) view.tabs[4]; // get reference to the catering tab from the view
        List<SpinnerNumberModel> spinnerModels = tab.getSpinnerModels(); // get reference to all SpinnerNumberModels from the view

        Map<Catering, Integer> cateringCounts = new HashMap<>(); // create a new map, which will contain every catering option with their desired amount
        for (int i = 0; i < spinnerModels.size(); i++) { // check every SpinnerNumberModel
            SpinnerNumberModel currentModel = spinnerModels.get(i); // get the current SpinnerNumberModel at index
            Catering equivalentCatering = KinoModel.ALL_CATERINGS.get(i); // get the catering at index from the model, which is equivalent to the index of the SpinnerNumberModel
            int value = (Integer)(currentModel.getValue()); // get the selected amount from the SpinnerNumberModel
            cateringCounts.put(equivalentCatering, value); // put catering as key with the selected amount as a value
        }
        model.setCatering(cateringCounts); // model receives map with catering-amount pairs
        view.update();
    }
}